### ISSUE TITLE
[Organizer Request] Add Saputro Aryulianto to KCD Indonesia

### ISSUE THREAD

**Issue by aryulianto** [cncf/kubernetes-community-days#585]
### Name of KCD chapter inquiring about

KCD Indonesia

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Saputro Aryulianto, aryuliantos@gmail.com, IMTEK, https://github.com/aryulianto, https://www.linkedin.com/in/aryulianto, Saputro Aryulianto (Ary) in CNCF Slack, https://community.cncf.io/u/mwc35p/#/about

### Tell us why you want to be added or removed from the KCD chapter

I, Saputro Aryulianto, would like to join as an organizer. I have experience as an organizer with KCD 2022.

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides/lives

- [X] I confirm I am local to or live near the city of the above-proposed KCD (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from NAME company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree to support the main content of the KCD remaining vendor-nuetral (do not mark if irrelevent to request)

### Remain an active organizer

- [X] I understand that in order to be considered a KCD organizer and get recognition, I need to attend the majority of the planning meetings. (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your KCD lineup/agenda

- [X] I will make an effort recruit diverse speakers in the KCD event agenda. (do not mark if irrelevent to request)
```[tasklist]
### Tasks
```

**Comment by bachrilq** [comment]
Yes @AudMonte01, I will add @aryulianto to our organizer, and our group chat. Thank you.

**Comment by AudMonte01** [comment]
Thank you, @bachrilq - should I add him as an organizer to the microsite here?
https://community.cncf.io/events/details/cncf-kcd-indonesia-presents-kcd-indonesia-2024/

**Comment by AudMonte01** [comment]
I have moved forward with adding @aryulianto as an organizer to the chapter so he is forward-facing on the website.

This issue/ticket is now closed.
